routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
    Route::get('admin', 'CP\TenantController@index')->name('admin');
    Route::get('admin/login', 'CP\TenantController@getLogin')->name('adminGetLogin');
    Route::post('admin/login', 'CP\TenantController@postLogin')->name('adminPostLogin');
    Route::get('admin/create', 'CP\TenantController@create')->name('adminGetCreate');
    Route::post('admin/create', 'CP\TenantController@store')->name('adminPostCreate');
});

app/Http/Controllers/CP/TenantController.php
<?php

namespace App\Http\Controllers\CP;

use App\Http\Controllers\Controller;
use App\Http\Requests\cp\StoreTenant;
use App\NotificationPreference;
use App\Tenant;
use App\TenantHostname;
use App\User;
use App\UserData;
use Bouncer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Novalis\Cloudflare\CloudflareFacade;

class TenantController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected function checkLogin($request)
    {
        if (!$request->exists('pass') && !session('loggedIn')) {
            return redirect()->route('adminGetLogin');
        }
    }

    public function index()
    {
        $this->checkLogin(new Request());
        \Landlord::removeTenant('tenant_id');
        $tenants = Tenant::with('tenantHostname', 'tenantSettings')->withCount(['tenantUsers' => function ($q) {
            $q->whereHas('roles', function ($i) {
                $i->where('name', 'student');
            })->whereFrozen(false);
        }])->paginate(50);
        return view('cp.list-tenants', ['tenants' => $tenants]);
    }

    public function getLogin(Request $request)
    {
        return view('cp.login');

    }

    public function postLogin(Request $request)
    {
        if ($request->pass = 'dlskjfoOInNXCKslepsoifdoufklwhjensLSidje&(*d872iousd9*uoil3kOOD*9s8jah3nbskkO)SJ839s8*#)@khjsdkc') {
            session('loggedIn', true);
            return redirect()->route('admin');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->checkLogin(new Request());
        return view('cp.create-tenant');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTenant $request)
    {
        $this->checkLogin($request);
        CloudflareFacade::addRecord($request->institutionHostname, '172.104.179.60');


        $tenant = new Tenant();
        $tenant->name = $request->institutionName;
        $tenant->email = $request->adminEmail;
        $tenant->user_id = 1;
        $tenant->save();


        $tenantHostname = new TenantHostname();
        $tenantHostname->hostname = $request->institutionHostname . '.edfim.com';
        $tenantHostname->tenant_id = $tenant->id;
        $tenantHostname->status = 1;
        $tenantHostname->save();

        $admin = new User();
        $admin->first_name = $request->adminFirstName;
        $admin->last_name = $request->adminLastName;
        $admin->username = $request->adminUserName;
        $admin->phone_no = $request->adminPhone;
        $admin->email = $request->adminEmail;
        $admin->password = Hash::make($request->adminPassword);
        $admin->gender = $request->gender ? $request->gender : 1;
        $admin->tenant_id = $tenant->id;
        $admin->save();


        $tenant->user_id = $admin->id;
        $tenant->save();

        $notification = new NotificationPreference();
        $notification->sms = 1;
        $notification->web = 1;
        $notification->email = 1;
        $notification->app = 1;
        $notification->user_id = $admin->id;
        $notification->save();

        $userData = new UserData();
        $userData->user_id = $admin->id;
        $userData->save();


        Bouncer::scope()->to($tenant->id);
        Bouncer::allow('user-admin')->to([
            'manage-all-staff',
            'view-all-staff',
            'manage-all-student',
            'view-all-student',
            'manage-all-parent',
            'view-all-parent',
            'view-all-role',
            'change-all-student-batch',
        ]);
        Bouncer::allow('student-admin')->to([
            'manage-all-student',
            'view-all-student',
            'manage-all-parent',
            'view-all-parent',
            'change-all-student-batch']);
        Bouncer::allow('staff-admin')->to([
            'manage-all-staff',
            'view-all-staff',
            'view-all-role']);
        Bouncer::allow('class-admin')->to([
            'manage-all-class',
            'view-all-class',
            'manage-all-batch',
            'view-all-batch',
            'manage-all-subject',
            'view-all-subject',
            'change-all-batch-class']);
        Bouncer::allow('class-teacher')->to([
            'view-timetable',
            'view-class',
            'view-batch',
            'view-subject',
            'view-student',
            'view-attendance', 'manage-attendance',
            'view-assignment', 'manage-assignment',
            'view-test', 'manage-test',
            'view-exam', 'manage-exam',
            'view-paper', 'manage-paper',
            'view-reputation', 'manage-reputation',
            'view-reputation-badge',
            'view-fine',
            'manage-fine',
        ]);
        Bouncer::allow('teacher')->to([
            'view-timetable',
            'view-class',
            'view-batch',
            'view-subject',
            'view-student',
            'view-attendance',
            'view-assignment', 'manage-subject-assignment',
            'view-test', 'manage-subject-test',
            'view-paper', 'manage-subject-paper',
            'view-exam',
            'view-reputation', 'manage-reputation',
            'view-reputation-badge',
            'view-fine',
            'manage-fine',
        ]);
        Bouncer::allow('attendance-admin')->to([
            'manage-all-timetable',
            'view-all-timetable',
            'manage-all-attendance',
            'view-all-attendance',
            'view-all-class',
            'view-all-batch',
            'view-all-student',
        ]);
        Bouncer::allow('assignment-admin')->to(['manage-all-assignment',
            'view-all-timetable',
            'view-all-assignment',
            'view-all-class',
            'view-all-batch',
            'view-all-subject',
            'view-all-student',
        ]);
        Bouncer::allow('assessment-admin')->to([
            'view-all-timetable',
            'manage-all-test',
            'view-all-test',
            'manage-all-exam',
            'view-all-paper', 'add-all-paper',
            'view-all-exam',
            'view-class',
            'view-batch',
            'view-subject',
            'view-all-student',
        ]);
        Bouncer::allow('reputation-admin')->to([
            'manage-all-reputation-badge',
            'view-reputation-badge'
        ]);
        Bouncer::allow('finance-admin')->to([
            'manage-all-fee',
            'view-all-fee',
            'manage-all-class-invoice',
            'view-all-class-invoice',
            'manage-all-student-invoice',
            'view-all-student-invoice',
            'view-all-class',
            'view-all-batch',
            'view-all-student']);
        Bouncer::allow('student')->to([]);
        Bouncer::allow('parent')->to([]);
        Bouncer::allow('system-admin')->everything();
        Bouncer::assign('system-admin')->to($admin);


        $settingsData = [
            [
                'key' => 'general.country',
//                'value' => $request->institutionCountry, // Max 7 days
                'value' => 'PK', // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'general.logo',
                'value' => 'none', // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'general.name',
                'value' => $request->institutionName, // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'general.address',
                'value' => $request->institutionAddress, // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'general.phone',
                'value' => $request->institutionPhone, // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'tenant.allowed_accounts',
                'value' => $request->institutionStudents, // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.schedule.weekly',
                'value' => '7', // Max 7 days
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'show_all_results',
//                0 hide results from other students, 1 show results
                'value' => 0,
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'finance.bank.name',
                'value' => '', //max 31 date
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'finance.bank.title',
                'value' => '', //max 31 date
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'finance.bank.number',
                'value' => '', //max 31 date
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.currency',
                'value' => '', //max 31 date
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.schedule.monthly',
                'value' => '05', //max 31 date
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.schedule.quarterly',
                'value' => '30-03', // days up to 30 - months up to 3
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.schedule.triannual',
                'value' => '30-04', // days up to 30 - months up to 4
                'tenant_id' => $tenant->id,
            ], [
                'key' => 'fee.schedule.biannual',
                'value' => '30-06', // days up to 30 - months up to 6

resources/views/cp/create-tenant.blade.php
@extends('cp.main')

@section('title', 'Create Institution Account')

@section('content-title')
    New Institution
@endsection

@section('content')
    <script>
      let errors = <?php echo json_encode($errors->all()) ?>;
      console.log(errors);
    </script>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="/api/admin/create" method="POST">
                <div class="box box-warning">
                    <div class="box-header ui-sortable-handle">
                        <i class="fa fa-envelope"></i>

                        <h3 class="box-title">Institution Details</h3>
                        <!-- tools box -->
                        <div class="pull-right box-tools">
                            {{--<button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">--}}
                            {{--<i class="fa fa-times"></i></button>--}}
                        </div>
                        <!-- /. tools -->
                    </div>
                    <div class="box-body">
                        {{csrf_field()}}
                        <div class="form-group {{$errors->has('institutionName')?'has-error':''}}">
                            <input type="text" name="institutionName" class="form-control"
                                   placeholder="Institution Name">
                            @if($errors->has('institutionName'))
                                <span class="help-block">{{$errors->first('institutionName')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('institutionAddress')?'has-error':''}}">
                            <input type="text" name="institutionAddress" class="form-control"
                                   placeholder="Institution Address">
                            @if($errors->has('institutionName'))
                                <span class="help-block">{{$errors->first('institutionName')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('institutionPhone')?'has-error':''}}">
                            <input type="tel" name="institutionPhone" class="form-control"
                                   placeholder="Institution Phone">
                            @if($errors->has('institutionPhone'))
                                <span class="help-block">{{$errors->first('institutionPhone')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('institutionStudents')?'has-error':''}}">
                            <input type="number" name="institutionStudents" class="form-control"
                                   placeholder="Students Count">
                            @if($errors->has('institutionStudents'))
                                <span class="help-block">{{$errors->first('institutionStudents')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('additionalSms')?'has-error':''}}">
                            <input type="number" name="additionalSms" class="form-control"
                                   placeholder="Additional SMS (per month)">
                            @if($errors->has('additionalSms'))
                                <span class="help-block">{{$errors->first('additionalSms')}}</span>
                            @endif
                        </div>
                        <div class="input-group {{$errors->has('institutionHostname')?'has-error':''}}">
                            <label>Portal Url</label>
                            <input type="text" name="institutionHostname" class="form-control"
                                   placeholder="schoolName">
                            <span class="input-group-addon">.edfim.com</span>
                            @if($errors->has('institutionHostname'))
                                <span class="help-block">{{$errors->first('institutionHostname')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('subscriptionPlan')?'has-error':''}}">
                            <label>Subscription Plan</label>
                            <select class="form-control" name="subscriptionPlan">
                                <option value="1">Basic</option>
                                <option value="2">Standard</option>
                                <option value="3">Premium</option>
                            </select>
                            @if($errors->has('subscriptionPlan'))
                                <span class="help-block">{{$errors->first('subscriptionPlan')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('paidFrom')?'has-error':''}}">
                            <input type="date" name="paidFrom" class="form-control" placeholder="Paid From">
                            @if($errors->has('Paid From'))
                                <span class="help-block">{{$errors->first('Paid From')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('paidTill')?'has-error':''}}">
                            <input type="date" name="paidTill" class="form-control" placeholder="Paid Till">
                            @if($errors->has('Paid Till'))
                                <span class="help-block">{{$errors->first('Paid Till')}}</span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="box box-info">
                    <div class="box-header ui-sortable-handle">
                        <i class="fa fa-envelope"></i>

                        <h3 class="box-title">Admin Account Details</h3>
                        <!-- tools box -->
                        <div class="pull-right box-tools">
                            {{--<button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">--}}
                            {{--<i class="fa fa-times"></i></button>--}}
                        </div>
                        <!-- /. tools -->
                    </div>
                    <div class="box-body">
                        <div class="form-group {{$errors->has('adminFirstName')?'has-error':''}}">
                            <input type="text" name="adminFirstName" class="form-control"
                                   placeholder="Admin First Name">
                            @if($errors->has('adminFirstName'))
                                <span class="help-block">{{$errors->first('adminFirstName')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminLastName')?'has-error':''}}">
                            <input type="text" name="adminLastName" class="form-control" placeholder="Admin Last Name">
                            @if($errors->has('adminLastName'))
                                <span class="help-block">{{$errors->first('adminLastName')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminUserName')?'has-error':''}}">
                            <input type="text" name="adminUserName" class="form-control" placeholder="Admin UserName">
                            @if($errors->has('adminUserName'))
                                <span class="help-block">{{$errors->first('adminUserName')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminEmail')?'has-error':''}}">
                            <input type="text" name="adminEmail" class="form-control" placeholder="Admin Email">
                            @if($errors->has('adminEmail'))
                                <span class="help-block">{{$errors->first('adminEmail')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminPhone')?'has-error':''}}">
                            <input type="text" name="adminPhone" class="form-control" placeholder="Admin Phone">
                            @if($errors->has('adminPhone'))
                                <span class="help-block">{{$errors->first('adminPhone')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminPassword')?'has-error':''}}">
                            <input type="password" name="adminPassword" class="form-control"
                                   placeholder="Admin Password">
                            @if($errors->has('adminPassword'))
                                <span class="help-block">{{$errors->first('adminPassword')}}</span>
                            @endif
                        </div>
                        <div class="form-group {{$errors->has('adminConfirmPassword')?'has-error':''}}">
                            <input type="password" name="adminConfirmPassword" class="form-control"
                                   placeholder="Admin Confirm Password">
                            @if($errors->has('adminConfirmPassword'))
                                <span class="help-block">{{$errors->first('adminConfirmPassword')}}</span>
                            @endif
                        </div>
                    </div>
                    <div class="box-footer clearfix">
                        <button type="submit" class="pull-right btn btn-default" id="sendEmail">Send
                            <i class="fa fa-arrow-circle-right"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/cp/list-tenants.blade.php
@extends('cp.main')

@section('title', 'Institutions Summary')

@section('content-title')
    Institutions Summary
@endsection

@section('content')
    <div class="col-12">
        <div class="box">
            <div class="box-header with-border">
                {{--<h3 class="box-title">Bordered Table</h3>--}}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Hostname</th>
                        <th>Users</th>
                        <th>Sms</th>
                        <th>Users</th>
                        <th>Package</th>
                    </tr>
                    @foreach ($tenants as $tenant)
                        <tr>
                            <td>{{$tenant->id}}</td>
                            <td>{{$tenant->name}}</td>
                            <td>{{$tenant->tenantHostname[0]->hostname}}</td>
                            <td>
                                @foreach($tenant->tenantSettings as $k)
                                    @if($k['key']==='tenant.allowed_accounts')
                                        <div class="progress progress-xs">
                                            <div class="progress-bar progress-bar-danger"
                                                 style="width:{{($tenant->tenant_users_count/$k['value'])*100}}%"></div>
                                        </div>
                                        {{$tenant->tenant_users_count}}/{{$k['value']}}
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                @foreach($tenant->tenantSettings as $k)
                                    @if($k['key']==='sms.quota')
                                        &nbsp;q:{{$k['value']}}
                                    @endif
                                    @if($k['key']==='sms.count')
                                        &nbsp;c:{{$k['value']}}
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            </td>
                            <td><span class="badge bg-red">55%</span></td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <!-- /.box-body -->
            {{ $tenants->links() }}
            {{--<div class="box-footer clearfix">--}}
            {{--<ul class="pagination pagination-sm no-margin pull-right">--}}
            {{--<li><a href="#">&laquo;</a></li>--}}
            {{--<li><a href="#">1</a></li>--}}
            {{--<li><a href="#">2</a></li>--}}
            {{--<li><a href="#">3</a></li>--}}
            {{--<li><a href="#">&raquo;</a></li>--}}
            {{--</ul>--}}
            {{--</div>--}}
        </div>
    </div>
@endsection

resources/views/cp/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/bootstrap/dist/css/bootstrap.min.css') }} ">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/font-awesome/css/font-awesome.min.css') }} ">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/Ionicons/css/ionicons.min.css') }} ">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('cp/dist/css/AdminLTE.min.css') }} ">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('cp/dist/css/skins/_all-skins.min.css') }} ">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/morris.js/morris.css') }} ">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/jvectormap/jquery-jvectormap.css') }} ">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }} ">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('cp/bower_components/bootstrap-daterangepicker/daterangepicker.css') }} ">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('cp/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }} ">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="{{ asset('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js') }} "></script>
    <script src="{{ asset('https://oss.maxcdn.com/respond/1.4.2/respond.min.js') }} "></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="/admin/login" method="post">
            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
                Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
                Google+</a>
        </div>
        <!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{ asset('cp/bower_components/jquery/dist/jquery.min.js') }} "></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('cp/bower_components/bootstrap/dist/js/bootstrap.min.js') }} "></script>

<!-- iCheck -->
{{--<</script>
script src="../../plugins/iCheck/icheck.min.js"></script>--}}
{{--<script>--}}
  {{--$(function () {--}}
    {{--$('input').iCheck({--}}
      {{--checkboxClass: 'icheckbox_square-blue',--}}
      {{--radioClass: 'iradio_square-blue',--}}
      {{--increaseArea: '20%' /* optional */--}}
    {{--});--}}
  {{--});--}}
</body>
</html>